function [fitresult, gof] = createFit(binranges, T)
%CREATEFIT1(BINRANGES,T)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : binranges
%      Y Output: T
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Oct-2017 16:07:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( binranges, T );
format long
% Set up fittype and options.
ft = fittype( 'a*x^1/(b*x+1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.155810767673063 0.199341671127337];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'T vs. binranges', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel binranges
% ylabel T
% grid on


