function [fitresult, gof] = createFitRational(l, F1,type,StartPoint)
%CREATEFIT4(L,F1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : l
%      Y Output: F1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-May-2018 15:12:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( l, F1 );

% Set up fittype and options.
ft = fittype(type);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';

opts.StartPoint=StartPoint;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'F1 vs. l', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel l
% ylabel F1
% grid on


